#!/bin/sh
# Copyright (c) 2007, Bart Trojanowski <bart@jukie.net>
#
# This script installs wmiirc-lua files into $HOME/.wmii-3.5

set -e

SRC_DIR="/etc/X11/wmii-3.5"
DST_DIR="${HOME}/.wmii-3.5"

SRC_WMIIRC="${SRC_DIR}/wmiirc.lua"
DST_WMIIRC="${DST_DIR}/wmiirc"

do_install () {
        INSTALL="install $@"

        ${INSTALL} -m 755 -d "${DST_DIR}"
        ${INSTALL} -m 744 -T "${SRC_WMIIRC}" "${DST_WMIIRC}"
}

while true ; do
        cmd=$1 ; shift
        case $cmd in 
            --force)
                do_install
                ;;
            --backup)
                do_install -b
                ;;
            *)
                break
                ;;
        esac
done

if [ -f "${SRC_WMIIRC}" ] ; then
        echo >&2 "System wide files for wmiirc-lua not installed."
        exit 1
fi

if [ -f "${DST_WMIIRC}" ] ; then
        echo >&2 "You already have files installed in ${DST_WMIIRC}."
        echo >&2 ""
        echo >&2 "Please select one of the following options and rerun this script:"
        echo >&2 ""
        echo >&2 "   $0 --force           - overwrite existing files"
        echo >&2 "   $0 --backup          - backup existing files"
        exit 1
fi


